[package]
name = "specjam"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
include = ["src", "head.txt", "README.md", "build.rs"]

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5", features = ["derive"] }
colored = "3.0.0"
serde_json = "1.0.135"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[build-dependencies]
codegen.workspace = true

[features]
default = ["tiny"]
tiny = ["codegen/tiny"]
full = ["codegen/full"]

[workspace]
members = ["codegen"]

[workspace.package]
version = "0.0.6"
edition = "2021"
description = "A tool spawns binary runner for testing the JAM spec"
license = "GPL-3.0"
documentation = "https://docs.rs/specjam"
repository = "https://github.com/spacejamapp/specjam"
homepage = "https://github.com/spacejamapp/specjam"

[workspace.dependencies]
codegen = { path = "codegen", package = "specjam-codegen", version = "0.0.6" }
